### ISSUE TITLE
Arena allocation

### ISSUE THREAD

**Issue by dullbananas** [roc-lang/basic-cli#104]
There should be a `Task.withArenaAlloc` function that initializes an arena allocator before running the task.

A while ago, I tried implementing it as an example: https://github.com/roc-lang/roc/pull/4943

In this implementation, the function takes `(U8 -> Task a err)` instead of `Task a err` to prevent allocations from being performed in the task expression before the arena allocator is initialized. A cleaner and more reliable solution would be for the function's type to be `a, (a -> Task b err) -> Task b err`.

There could also be a similar function of type `a, (a -> b) -> b` for when no tasks need to be run.

**Comment by Anton-4** [comment]
Hi @dullbananas,
I've started a discussion on this proposed addition on [zulip](https://roc.zulipchat.com/#narrow/stream/304641-ideas/topic/basic-cli.20Task.2EwithArenaAlloc/near/386349854).

**Comment by Anton-4** [comment]
I made these comments in the discussion:
> While we've talked about supporting functionality like this with roc, it seems out of scope for basic-cli. I want all of basic-cli to be super reliable across all architectures and operating systems supported by roc. Allowing multiple ways of memory allocation seems like it would make that task a lot harder.

> I could definitely see something like `Task.withArenaAlloc` be added in a future industrial-cli though.

Richard agreed and no one else opposed so I'm closing this issue. I hope this make sense to you @dullbananas :heart:
