### ISSUE TITLE
Change `main` type to `Task {} *`

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/basic-cli#12]
The idea here is to make `main` more beginner-friendly without noticeably affecting things experienced users.

If `main` has the type `Task {} *` (which it achieves by translating any unhandled `Task` errors into crashes automatically), then beginners don't need to learn about how to gracefully handle errors right away. They can pretty much just ignore errors and get a crash if something goes wrong, allowing them to focus on learning other things - e.g. how to chain tasks together.

Advanced users can continue to annotate their `main` as `main : Task {} []` (which of course is compatible with `main : Task {} *`) and then they'll still get exhaustiveness errors for any task errors they forgot to handle, just like today!

**Comment by agu-z** [comment]
This is a great idea! 

I made this change locally, but without an `a -> Str` function, I can't `crash` with a suitable error string. 

Are there any plans to provide something like that? Alternatively, `crash` could take an unbound `a` instead of `Str`.

**Comment by agu-z** [comment]
https://roc.zulipchat.com/#narrow/stream/304641-ideas/topic/display.20and.20log/near/350745735

**Comment by rtfeldman** [comment]
Closing in favor of https://github.com/roc-lang/basic-cli/issues/52 which seems to have more benefits overall!
