### ISSUE TITLE
Add `Path.isDir`, `isFile`, `isSymLink`...

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/basic-cli#145]
- [ ] `isDir : Path -> Bool`
- [ ] `isFile: Path -> Bool`
- [ ] `isSymLink: Path -> Bool`
- [ ] `type: Path -> [IsFile, IsDir, IsSymLink]`

**Comment by lindskogen** [comment]
I could take a stab at this!

**Comment by Anton-4** [comment]
Thanks @lindskogen, go for it :)
