### ISSUE TITLE
Dir.list function is crashing on linux

### ISSUE THREAD

**Issue by salarii** [roc-lang/basic-cli#2]
ubuntu linux, Dir.list is crashing with error
Dir.list...
munmap_chunk(): invalid pointer
roc nightly pre-release, build from commit 1aa928b on Sa 19 Nov 2022 09:32:56 UTC

**Comment by salarii** [comment]
platrorm ubuntu 20.04.5

**Comment by Anton-4** [comment]
This issue is likely related to https://github.com/roc-lang/roc/issues/4266

**Comment by Anton-4** [comment]
I believe #136 should have fixed this.
