### ISSUE TITLE
Task.sequence runs the tasks in reverse order

### ISSUE THREAD

**Issue by ageron** [roc-lang/basic-cli#235]
I was surprised to see that `Task.sequence` runs the tasks in reverse order. If this is working as expected, then the documentation should clearly state this.

For example:

```roc
app [main] { cli: platform "https://github.com/roc-lang/basic-cli/releases/download/0.12.0/Lb8EgiejTUzbggO2HVVuPJFkwvvsfW6LojkLR20kTVE.tar.br" }

import cli.Task
import cli.Stdout

run : U8 -> Task.Task _ _
run = \n ->
    n |> Num.toStr |> Stdout.line!

main =
    _ = [1,2,3] |> List.map run |> Task.sequence!
    Task.ok {}
```

Prints this:

```bash
3
2
1
```

**Comment by lukewilliamboswell** [comment]
Fixed in https://github.com/roc-lang/roc/pull/6836 builtin-task commit aabe75ff87bd105e293eb1e7c6944f9fc6141ffd
