### ISSUE TITLE
`basic-cli` is using an outdated version of `roc-std`

### ISSUE THREAD

**Issue by bhansconnect** [roc-lang/basic-cli#25]
The lock file has been keeping basic-cli using a version of `roc-std` from mid January. As such, it will break if passed a seamless slice.

I think it may be worth removing the lock file from basic-cli so that we always pull in the latest roc-std when publishing it. Otherwise, maybe we should add a `cargo update` to the publishing process? Fundamentally we want this to stay in sync.

**Comment by Anton-4** [comment]
@bhansconnect I actually had the roc commit specified in the Cargo.toml, not in the Cargo.lock file. I like to keep the lock file around for reproducibility. I actually had automated tests that detected this failure but I didn't have notifications set up for it, I've set a reminder to check them daily until I set up notifications.
