### ISSUE TITLE
roc-on GitLab MR proxy: Honor basic-cli license for adapted files 

### ISSUE THREAD

**Issue by JanCVanB** [roc-lang/basic-cli#269]
Thanks for this great platform! I'm writing [an AGPLv3-licensed Roc platform](https://gitlab.com/JanCVanB/roc-on) that's based on basic-cli.

Do you feel this MR sufficiently honors your copyright, or would you like me to go further in any way? https://gitlab.com/JanCVanB/roc-on/-/merge_requests/2/diffs

I'm particularly concerned about modifications like this going perhaps too far in a whitewashing direction: https://gitlab.com/JanCVanB/roc-on/-/commit/426e0342670121b61f2dbb8132531a32f5723396?page=2#e2ce0bcc5ade97e69383b5ab1dcaf1e60510fde6

**Comment by rtfeldman** [comment]
I think as long as you mention somewhere that it's based on basic-cli, and that basic-cli uses the UPL-1.0 license, you're all set!

As far as I know, nothing beyond attribution is necessary - everything else is entirely up to you! 😄
