### ISSUE TITLE
Basic-cli 0.16.0 uses Str.split which is not in builtins

### ISSUE THREAD

**Issue by gamebox** [roc-lang/basic-cli#270]
Because of https://github.com/roc-lang/basic-cli/blob/main/platform/Arg/Help.roc#L342

I get the following when compiling the `Arithmetic` example from roc-lang/examples:

```text
 …/roc-examples/examples/Arithmetic   main !   09:09
❯ ../../../roc/target/debug/roc build

── NOT EXPOSED in .../O00IPk-Krg_diNS2dVWlI0ZQP794Vctxzv0ha96mK0E/Arg/Help.roc ─

The Str module does not expose `split`:

342│      |> Str.split "\n"
             ^^^^^^^^^

Did you mean one of these?

    Str.splitOn
    Str.repeat
    Str.trim
    Str.splitLast

────────────────────────────────────────────────────────────────────────────────

1 error and 0 warnings found in 1066 ms
 while successfully building:

    main
```

**Comment by gamebox** [comment]
Is this platform not meant to be compatible with latest Roc compiler?

**Comment by Anton-4** [comment]
Linking to zulip discussion https://roc.zulipchat.com/#narrow/channel/302903-platform-development/topic/Platform.20.2F.20Language.20version.20compatibility/near/483949925

I now realize I forgot to merge the split-update branch into main https://github.com/roc-lang/basic-cli/pull/272 :sweat_smile:

**Comment by Anton-4** [comment]
https://github.com/roc-lang/basic-cli/pull/272 is merged
