### ISSUE TITLE
How is `examples/http-get-json.roc` intended to be run?

### ISSUE THREAD

**Issue by JanCVanB** [roc-lang/basic-cli#284]
I see `localhost:8000` and `{ "foo": "something" }` mentioned both [here](https://github.com/roc-lang/basic-cli/blob/3f270597a6617c92247dede5d5c0524aa326c108/examples/http-get-json.roc#L14) and [here](https://github.com/roc-lang/basic-cli/blob/3f270597a6617c92247dede5d5c0524aa326c108/platform/Http.roc#L172), but I'm unsure whether this example is intended to be runnable and print that value.

**Comment by JanCVanB** [comment]
Gotcha, thanks!

**Comment by Anton-4** [comment]
I added a comment to clarify this https://github.com/roc-lang/basic-cli/commit/f1b8fd6450a14d8ff0566ecc01dd42e4603bef97
