### ISSUE TITLE
Is `examples/task-list.roc` still relevant?

### ISSUE THREAD

**Issue by JanCVanB** [roc-lang/basic-cli#285]
I see that [this example](https://github.com/roc-lang/basic-cli/blob/3f270597a6617c92247dede5d5c0524aa326c108/examples/task-list.roc) was updated with purity inference to remove Task stuff, but then I wonder if it now serves any demonstrative purpose. Does it still do anything unique from the other tests? Does it just need an updated name?

**Comment by lukewilliamboswell** [comment]
Its purpose is to use recursion to do the same thing that `Task.forEach` does, do a repetitive task for a list of things.

It could maybe be renamed and add more documentation or explanation... though I'm not sure it's necessary. We tend to prefer using `roc-land/examples` for explaining concepts and documentation, I feel like these examples serve more a testing purpose.

**Comment by JanCVanB** [comment]
Okie dokie, then erring on the side of leaving it alone sounds good.
