### ISSUE TITLE
Corrections for record-builder.roc

### ISSUE THREAD

**Issue by Ivo-Balbaert** [roc-lang/basic-cli#93]
When trying to compile this there were some minor changes to make:
- Task signature: I32 -> U32
- Task.ok --> Task.succeed
- Task.mapErr --> Task.mapFail

I tried to fork and do a pull request, but today the whole business with SSH keys needed for that didn't want to work for me.
So here is the update code:

```
app "test"
    packages { pf: "https://github.com/roc-lang/basic-cli/releases/download/0.4.0/DI4lqn7LIZs8ZrCDUgLK-tHHpQmxGF1ZrlevRKq5LXk.tar.br" }
    imports [
        pf.Stdout, pf.Task.{ Task },
    ]
    provides [main] to pf

main =
    myrecord : Task { apples : List Str, oranges : List Str } U32
    myrecord = Task.succeed {
        apples: <- getFruit Apples |> Task.batch,        
        oranges: <- getFruit Oranges |> Task.batch,      
    }

    { apples, oranges } <- myrecord |> Task.await        

    "Apples: "                                           
    |> Str.concat (Str.joinWith apples ", ")
    |> Str.concat "\n"
    |> Str.concat "Oranges: "
    |> Str.concat (Str.joinWith oranges ", ")
    |> Stdout.line
    |> Task.mapFail \_ -> 1

getFruit : [Apples, Oranges] -> Task (List Str) *
getFruit = \request ->
    when request is
        Apples -> Task.succeed ["Granny Smith", "Pink Lady", "Golden Delicious"]
        Oranges -> Task.succeed ["Navel", "Blood Orange", "Clementine"]

# =>
# Apples: Granny Smith, Pink Lady, Golden Delicious
# Oranges: Navel, Blood Orange, Clementine
```

**Comment by Anton-4** [comment]
Hi @Ivo-Balbaert,

On the main branch there have been some updates compared to the latest 0.4.0 release. You can easily view the 0.4.0 examples if you:
1. click on the dropdown at the top left displaying "main"
2. Selects the "Tags"
3. Click 0.4.0

To prevent this issue we can display the 0.4.0 by default if you go to https://github.com/roc-lang/basic-cli, I'll ask on Zulip to check if others agree with this change.

**Comment by Ivo-Balbaert** [comment]
Ok; thank you. In my opinion 0.4.0 by default would be good.
